### PR TITLE
Passing error message from saga to a form

### PR DESCRIPTION
**Pull request by sergeyzwezdin**
As mentioned in https://github.com/mhssmnn/redux-form-saga/issues/5 for the moment there is no way to pass error message from saga/promise to the form. That is because of whole action passed to `reject` function while `redux-form` expects `SubmissionError` object there.

I've applied small fix to resolve the issue by passing `payload` property to `reject` instead of whole message. Please note if there is no `payload` property in the action nothing will changed as well.

So, now to pass error message to `redux-form` need to run following code in the saga:

```javascript
yield put({
    type: FORM_FAILURE,
    payload: new SubmissionError({ _error: 'Some error message which will be passed to the form' })
});
```

Code snippet for render method of the form:

```javascript
render() {
    const { handleSubmit,
            submitting,
            submitSucceeded,
            submitFailed,
            error } = this.props;
    return <form ... onSubmit={handleSubmit}>

    	{/* Fields */}

    	{ submitFailed && !submitting && error
        ? <div>{error}</div>
        : null
        }

    	</form>;
}
```

### CODE REVIEW

**Comment by mhssmnn** [comment]
@sergeyzwezdin would be happy to, could you fix the conflicts please?

**Comment by sergeyzwezdin** [comment]
@mhssmnn done

**Comment by mhssmnn** [comment]
On second thought, it might be better to handle both the success and failure behaviours in the same way. So that the promise resolve and reject both get the payload from the action?

```js
  if (winner.success) {
    yield call(resolve, winner.success.payload);
  } else {
    yield call(reject, winner.fail.payload);
  }
```

**Comment by afitiskin** [comment]
@sergeyzwezdin, FYI: I fixed this bug in forked repo (published to NPM as [redux-saga-actions](https://www.npmjs.com/package/redux-saga-actions). A bit more info in #5.

**Comment by sergeyzwezdin** [comment]
@mhssmnn You're right. I've added it to PR as well.

@afitiskin Yes, I saw this at #5, but it would be better to see these changes in original repo as well :-)

**Pull request merged**
